language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "create database aszist_test;" -U postgres
  - bundle exec rake db:migrate
script: bundle exec rake test
notifications:
  email: p@rdln.net
